[package]
name = "gamemaker_rust"
version = "0.3.0"
edition = "2021"
description = "A 2D game engine and editor built with Rust and Bevy"
authors = ["GameMaker Rust Team"]
license = "MIT"

[dependencies]
bevy = "0.13"
bevy_egui = "0.25"
egui_dock = "0.11"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
rfd = "0.11"
chrono = { version = "0.4", features = ["serde"] }